### ISSUE TITLE
Service failed to start after upgrade.

### ISSUE THREAD

**Issue by seriv** [m3047/trualias#6]
```
$ cat /etc/redhat-release 
Fedora release 37 (Thirty Seven)
$ python --version
Python 3.11.0
$ git show -q
commit aec14c3875a1846b3359b1c5dc0815ee52b9fb87 (HEAD -> master, origin/master, origin/HEAD)
Author: Fred Morris <consulting@m3047.net>
Date:   Thu Oct 15 11:38:43 2020 -0700

    Instructions for both tcp_table_server and tcp_virtual_server.
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        python/trualias.conf

nothing added to commit but untracked files present (use "git add" to track)
$ sudo systemctl start trualias
$ sudo journalctl -n 24 trualias
Failed to add match 'trualias': Invalid argument
$ sudo journalctl -n 24 -u trualias
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Scheduled restart job, restart counter is at 4.
Nov 22 18:39:08 spectr.org systemd[1]: Stopped trualias.service - Trualias Postfix TCP Virtual Service.
Nov 22 18:39:08 spectr.org systemd[1]: Started trualias.service - Trualias Postfix TCP Virtual Service.
Nov 22 18:39:08 spectr.org python3[18120]: detected unhandled Python exception in '/usr/local/share/trualias/python/tcp_virtual_server.py'
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]: Traceback (most recent call last):
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:   File "/usr/local/share/trualias/python/tcp_virtual_server.py", line 108, in <module>
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:     base_server.main(allocate_context, base_server.resolve_config_files(CONFIG_FILE), config_loader)
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:   File "/usr/local/share/trualias/python/tcp_table_server.py", line 353, in main
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:     server = loop.run_until_complete(coro)
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:   File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:     return future.result()
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:            ^^^^^^^^^^^^^^^
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:   File "/usr/lib64/python3.11/asyncio/streams.py", line 85, in start_server
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:     return await loop.create_server(factory, host, port, **kwds)
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 22 18:39:08 spectr.org tcp_virtual_server.py[18120]: TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Main process exited, code=exited, status=1/FAILURE
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Failed with result 'exit-code'.
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Scheduled restart job, restart counter is at 5.
Nov 22 18:39:08 spectr.org systemd[1]: Stopped trualias.service - Trualias Postfix TCP Virtual Service.
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Start request repeated too quickly.
Nov 22 18:39:08 spectr.org systemd[1]: trualias.service: Failed with result 'exit-code'.
Nov 22 18:39:08 spectr.org systemd[1]: Failed to start trualias.service - Trualias Postfix TCP Virtual Service.
```

**Comment by m3047** [comment]
Salutations, customer! ;-) I'll take a look.

**Comment by m3047** [comment]
I'd appreciate any input on making this a non-breaking change. If anybody has any...

**Comment by m3047** [comment]
This is fixed for `tcp_table_server.py` and `tcp_virtual_server.py` at c5bbea957fc7c20aa64e82df7b435d877cace770. It should remain backwards compatible to 3.6 (I don't know of anyone running anything earlier than 3.6).

That said, I'm not running 3.11 in production anywhere.

I did not update `milter_server.py` because I haven't heard from the milter folks in a while.
